// This file was autogenerated by `parameters.py`. DO NOT TOUCH.
`define FP_INTEGER 8
`define FP_FRACTION 24

// This file is meant to be included inside modules that have a
// `DATAWIDTH` parameter, otherwise these functions will fail to compile.

// TODO: handle overflow and saturate properly
// fp addition can only overflow when sign(a) != sign(b)
// fp multiplication can overflow anytime

function [DATAWIDTH-1:0] fmul;
    input [DATAWIDTH-1:0] a;
    input [DATAWIDTH-1:0] b;
    reg [DATAWIDTH*2-1:0] extended_a;
    reg [DATAWIDTH*2-1:0] extended_b;
    reg [DATAWIDTH*2-1:0] tmp;
    begin
        extended_a[0+:DATAWIDTH] = a;
        extended_a[DATAWIDTH+:DATAWIDTH] = {DATAWIDTH{a[DATAWIDTH-1]}};
        extended_b[0+:DATAWIDTH] = b;
        extended_b[DATAWIDTH+:DATAWIDTH] = {DATAWIDTH{b[DATAWIDTH-1]}};
        tmp = extended_a * extended_b;
        fmul = tmp >> `FP_FRACTION;
    end
endfunction

function [DATAWIDTH-1:0] fadd;
    input [DATAWIDTH-1:0] a;
    input [DATAWIDTH-1:0] b;

    begin
        fadd = a + b;
    end
endfunction